### ISSUE TITLE
Setting up the Google Maps API

### ISSUE THREAD

**Issue by jhsu802701** [eebbesen/minutes_maid#70]
I'm trying to set up the app on my local machine, but I keep getting errors because VCR does not recognize the URL https://maps.googleapis.com/maps/api/place/autocomplete/json?input=1600%20Grand%20Ave%20Saint%20Paul,%20MN&key=MY_KEY_VALUE_HERE&language=en .  I tried getting a Google Maps API key and using it, but this doesn't fix things.  Am I missing a key step?

**Comment by eebbesen** [comment]
@jhsu802701 see https://github.com/eebbesen/minutes_maid/pull/83 -- this should address this issue. Please let me know if it does not!

Previously VCR tests were using my actual Google Maps API key. I've invalidated that key, set it in test_helper.rb and also made it dynamically-based in the VCR cassette files for additional robustness.
